### ISSUE TITLE
[Question] Can 'useGA4React' hook be used for sub-domains as well ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [unrealmanu/ga-4-react#10]
While going through [GA documentation](https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingSite), they do support multiple sub domains for which events can be recorded. 

We have multiple domains (_one for each customer, `a.example.com`, `b.example.com`, etc._ ), and we want to roll up the data collected. This is in addition to per customer data collection.

I tried the same using the below example

```
const Example = () => {
  const ga4React1 = useGA4React('GA_CODE_I', {}, []); // GA CODE, optional, if empty try to get from globals
  console.log(ga4React1);
  . . .
  const ga4React2 = useGA4React('GA_CODE_II', {}, []); // GA CODE, optional, if empty try to get from globals
  console.log(ga4React2);
  . . .
  return <>{JSON.stringify(ga4React)}</>;
};
```

But the second object always found to be null. Is there anything missed out in above configuration ?

**Comment by unrealmanu** [comment]
I have not particularly tested this use, so if you find any problems, report them to me that I correct it, but I suggest you try this:

 const ga = useGA4React("G-1JXXXXX,G-2JXXXXX");
 
 or
 
  const ga = useGA4React(["G-1JXXXXX","G-2JXXXXX"]);
  
  and then to do that. you have to use the function directly `gtag`
