### ISSUE TITLE
[Error] GA4React is being initialized

### ISSUE THREAD

**Issue by hashimwebsul** [unrealmanu/ga-4-react#11]
i am trying to send pageview but i get this error when i am navigating to any page
![image](https://user-images.githubusercontent.com/74176187/110093879-3669de00-7dc1-11eb-901f-86ddc0e414b7.png)

`  useEffect(() => {
    const ga4react = new GA4React('G-1JXXXXX');
    ga4react.initialize().then((ga4) => {
      ga4.pageview(location.path + location.search)
    }, (err) => {
      console.log('error sending page view', err)
    })
  }, [location])`

**Comment by unrealmanu** [comment]
You should only initialize ga-4-react once, so every react life cycle, you restart it, it's not allowed.


for example:

`import React from "react";
import ReactDOM from "react-dom";
import GA4React, { useGA4React } from "ga-4-react";

const ga4react = new GA4React("G-1JXXXXX");

function MyApp() {
  const ga = useGA4React();
  console.log(ga);

  return <div className="App">hi!</div>;
}

(async () => {
  await ga4react.initialize();

  ReactDOM.render(
    <React.StrictMode>
      <MyApp />
    </React.StrictMode>,
    document.getElementById("root")
  );
})();
`

**Comment by unrealmanu** [comment]
otherwise, let the library start by itself:
```
import React from "react";
import ReactDOM from "react-dom";
import { useGA4React } from "ga-4-react";

function MyApp() {
  const ga = useGA4React("G-1JXXXXX");
  console.log(ga);

  return <div className="App">hi!</div>;
}

ReactDOM.render(
  <React.StrictMode>
    <MyApp />
  </React.StrictMode>,
  document.getElementById("root")
);

```
