### ISSUE TITLE
ga-4-react + react Router (hash Router)

### ISSUE THREAD

**Issue by AlexVanK** [unrealmanu/ga-4-react#15]
Hello,

this is my current setup.
![image](https://user-images.githubusercontent.com/56647386/113658712-87921980-966e-11eb-9b9e-7f431b4fcc52.png)

and in my app component I generate pages dynamically using React Router (hash Router).
Is it possible to manually trigger a page view so that it gets tracked in GA4?

For example:
![image](https://user-images.githubusercontent.com/56647386/113658806-b7412180-966e-11eb-9033-ef91d64fd988.png)
![image](https://user-images.githubusercontent.com/56647386/113658938-09824280-966f-11eb-832a-b4d794d58af0.png)

**Comment by unrealmanu** [comment]
Hi Alex,
I'll add an example, I hope it helps

`import React from 'react';
import ReactDOM from 'react-dom';
import GA4React from 'ga-4-react';
import { HashRouter, Link } from 'react-router-dom';

const ga4react = new GA4React('G-1JXXXXX');

function MyApp() {
    return (
        <div>
            <Link to="/link1">Link1</Link>
            <br />
            <Link to="/link2">Link2</Link>
            <br />
            <Link to="/link3">Link3</Link>
            <br />
        </div>
    );
}

(async () => {
    await ga4react.initialize();

    window.onhashchange = () => {
        console.log(window.location.hash);
        ga4react.pageview(window.location.hash);
    };

    ReactDOM.render(
        <React.StrictMode>
            <HashRouter basename="/calendar">
                <MyApp />
            </HashRouter>
        </React.StrictMode>,
        document.getElementById('root')
    );
})();`

**Comment by AlexVanK** [comment]
```
window.onhashchange = () => {
    console.log(window.location.hash);
    ga4react.pageview(window.location.hash);
};
```

This is the magic I was looking for.
With this module, is possible to pass custom data to GA? For example a custom page's title?

Thank you for your help!

**Comment by unrealmanu** [comment]
You can pass the same information that is there in the google documentation

https://developers.google.com/analytics/devguides/collection/gtagjs/pages

good continuation, if you need, write, as soon as I can, I answer
