### ISSUE TITLE
Send file_download event and pass parameters

### ISSUE THREAD

**Issue by AlexVanK** [unrealmanu/ga-4-react#17]
Hi,

This is in reference to the this last comment:
https://github.com/unrealmanu/ga-4-react/issues/15#issuecomment-814275945

---

I am trying to send the event `file_download` to GA4 this way:
![image](https://user-images.githubusercontent.com/56647386/114424174-dadffc80-9b85-11eb-882c-cc6a63aaab00.png)
using the first two arguments: `action` and `label`
![image](https://user-images.githubusercontent.com/56647386/114425096-bf292600-9b86-11eb-95b5-150b2e3178d8.png)

Along with the event I would like to send some other metadata. For example `page_referrer` - as a parameter, however, when I debug the `event()` method, I see that there are only 4 arguments to be passed.
![image](https://user-images.githubusercontent.com/56647386/114425059-b59fbe00-9b86-11eb-8d89-3f44c0d938f9.png)

Yet, on GA4 report, there seem to be a long list of parameters that could be captured from one single event:
![image](https://user-images.githubusercontent.com/56647386/114424947-96a12c00-9b86-11eb-8759-871d9ac0e7f2.png)

Am I doing something wrong here, or missing some basic concepts about GA4?

**Comment by unrealmanu** [comment]
using the gtag function, as in google documentation
https://developers.google.com/analytics/devguides/collection/gtagjs/events

` ga4.gtag('event','pageview','path') // or your custom gtag event`
