### ISSUE TITLE
Automatically Logout in React App

### ISSUE THREAD

**Issue by Waingapucoder** [unrealmanu/ga-4-react#18]
Excuse me, thanks for creating this cool library.

I had a problem in my React App, where when I implemented the current version of Google Analytics (v4) with the `ga-4-react` library, my React App often **logged out automatically** when there was a change in my code during development. But if it's refreshed, it doesn't log out automatically. Does this have any effect from this library?
If so, how do you solve it ?

Thank you.

**Comment by unrealmanu** [comment]
I don't think ga 4 react can affect the connection of your react app, maybe the problem is elsewhere

**Comment by unrealmanu** [comment]
in case try to provide me with some other details, screenshots of the problem etc, if I can think of something I will tell you

**Comment by Waingapucoder** [comment]
![Screenshot from 2021-05-05 11-36-35](https://user-images.githubusercontent.com/62747828/117094436-5f452a00-ad96-11eb-8157-e494793fd01e.png)

I think this problem comes from the `GA4React Timeout at ga4manager.tsx in line 182` error

If I may know, why did this happen? and how to avoid it?

Thank you.

**Comment by unrealmanu** [comment]
I'm sorry I don't know how to help you, I'm certainly not dependent on ga-4-react
