### ISSUE TITLE
<script> tag not always added to header

### ISSUE THREAD

**Issue by kobesnyder** [unrealmanu/ga-4-react#3]
For some scenarios and some browsers, the document.readyState is never set to 'interactive', in which case the google tag manager script isn't added to the head in lib\ga4manager.tsx.

Adding a fallback for readyState == 'complete' fixed this issue for me.

Example:
```
let scriptAdded = false;
document.onreadystatechange = function() {
    if (scriptAdded) {
        return;
    }
    switch (document.readyState) {
        case 'interactive':
        case 'complete':
            head.appendChild(scriptAsync);
            scriptAdded = true;
            break;
    }
};
```

**Comment by unrealmanu** [comment]
Hello, in the meantime, thanks for reporting.
Looking at the documentation https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
it seems to me that the browser always goes from the "interactive" state, if the script is requested/initialized, before this state.

But if not, do you have a reference that talks about the cases in question? a document? a link? example? thk

**Comment by unrealmanu** [comment]
@kobesnyder if in doubt, I still did a general refactor, to improve the code, and I improved the management of cases, including the reporting :)
let me know if it repeats, close, have a nice day

**Comment by kobesnyder** [comment]
@unrealmanu much appreciated, thanks! Your improvements fixed the issue I was seeing.

I was trying to reproduce the issue with a minimal test app, but no luck, so it must have been related to the specific (very large) client app I am using ga-4-react for. And I was only seeing the issue using Firefox **Developer Edition**, so probably a strange edge case anyway.

Regardless, many thanks for the quick turnaround on the refactoring!
