### ISSUE TITLE
Can't get it to work :/

### ISSUE THREAD

**Issue by chriskaya** [unrealmanu/ga-4-react#9]
Hi there,

First of all, thank you for this lib :)
I guess the issue is between my chair and keybard, but I can't seem to get this working.

Here's an excerpt from my code:

```
import { GA4React } from 'ga-4-react';

const App = () => {
  const ga4react = new GA4React('MY GA CODE');
  ga4react.initialize()
    .then((ga4) => {
      console.log('ga4', ga4);
    })
    .catch((err) => {
      console.error('ga4', err)
    });
  return <p>Test</p>
};
```

Anytime I try this, I get a timeout error:
`Error: GA4React Timeout at ga4manager.tsx:178`

No `<script>` tag is being added to `<head>`, no call is being done to analytics servers.

What am I missing?

Thx for your help!

**Comment by unrealmanu** [comment]
Hi, are you trying to use it on a platform like codesanbox.io by any chance?
I have encountered problems on these platforms.
Also be careful with VPNs and antivirus.

in case you are using it on browser, try version 0.1.28 which fixes some startup problems.

If you don't solve, let me know what browser you are trying on and what version, which I do tests.

**Comment by chriskaya** [comment]
No I tried on my computer with `npm start`, and published on a test server with `react-scripts build`.
App was built with CRA, and I'm on Chrome 88.0.4324.150
I'm off right now but Monday I'll try other browsers and/or computers, with and without antivirus to get more info.
Thanks for your help :)

**Comment by chriskaya** [comment]
I did some testing today, it worked a few times (GA4React got initialized), but really inconsistently and without any observable pattern :/
I think I'm gonna stick with the basic way for now (manually adding the script tag and calling window.gtag).
Thank you for your work, I'll be watching this lib closely :)
